package services.sunsetrise;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-11-02T14:43:10.697+01:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET/", name = "SunSetRiseServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface SunSetRiseServiceHttpPost {
}
