
package services.sunsetrise;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-11-02T14:43:10.680+01:00
 * Generated source version: 3.1.2
 * 
 */
public final class SunSetRiseServiceHttpGet_SunSetRiseServiceHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webserviceX.NET/", "SunSetRiseService");

    private SunSetRiseServiceHttpGet_SunSetRiseServiceHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SunSetRiseService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SunSetRiseService ss = new SunSetRiseService(wsdlURL, SERVICE_NAME);
        SunSetRiseServiceHttpGet port = ss.getSunSetRiseServiceHttpGet();  
        

        System.exit(0);
    }

}
