package services.sunsetrise;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-11-02T14:43:10.692+01:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET/", name = "SunSetRiseServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SunSetRiseServiceSoap {

    /**
     * Get Sunset and Sunrise time for any location in the world<br><b>Longitude:</b>Positive in Western Hemisphere,Negative in Eastern Hemisphere<br><b>Latitude:</b>Positive in Northern Hemisphere,Negative in Southern Hemisphere
     */
    @WebMethod(operationName = "GetSunSetRiseTime", action = "http://www.webserviceX.NET/GetSunSetRiseTime")
    @RequestWrapper(localName = "GetSunSetRiseTime", targetNamespace = "http://www.webserviceX.NET/", className = "services.sunsetrise.GetSunSetRiseTime")
    @ResponseWrapper(localName = "GetSunSetRiseTimeResponse", targetNamespace = "http://www.webserviceX.NET/", className = "services.sunsetrise.GetSunSetRiseTimeResponse")
    @WebResult(name = "GetSunSetRiseTimeResult", targetNamespace = "http://www.webserviceX.NET/")
    public services.sunsetrise.LatLonDate getSunSetRiseTime(
        @WebParam(name = "L", targetNamespace = "http://www.webserviceX.NET/")
        services.sunsetrise.LatLonDate l
    );
}
